### ISSUE TITLE
Error when app goes over some files

### ISSUE THREAD

**Issue by eleriaqueen** [Shadowth117/PSOBMLExtract#1]
Hello, thanks for making PSO BML Extract ! 
It gives an error when extracting some PSOGC BML files but doesn't crash, it still extracts some stuff from of those though.
![Screenshot 2020-10-05 080221](https://user-images.githubusercontent.com/4411178/95044995-31edac00-06e1-11eb-855c-a96c00ca41b7.png)

**Comment by Shadowth117** [comment]
I'm like 99% sure it was due to a dumb issue in which I didn't properly handle filenames in certain cases. Can you try this latest build and let me know that it works alright?
[PSOBmlExtract.zip](https://github.com/Shadowth117/PSOBMLExtract/files/5325732/PSOBmlExtract.zip)

SAMDL in this tool pack should open non .xj PSO model files I think by the way: http://info.sonicretro.org/SA_Tools

**Comment by eleriaqueen** [comment]
Yep, seems to work okay now, no error. Files are extracted.
Same file as in previous screenshot show this in debug file
`BML File Count: 3
**obj_o_sea_container_hahen01_r.gj**
142
0
240
0
0
**obj_o_sea_container_hahen02_r.gj**
169
0
2A0
0
0
**obj_o_sea_container_r.gj**
620
0
EC0
0
0
Actual Offsets
obj_o_sea_container_hahen01_r.gj offset start, end: 
800
942
obj_o_sea_container_hahen02_r.gj offset start, end: 
960
AC9
obj_o_sea_container_r.gj offset start, end: 
AE0
1100
`

Thanks a lot for the link too !

**Comment by Shadowth117** [comment]
No problem, hope it helps. That other tool should read animations that aren't from blue burst too. 
If you run into any more problems, feel free to drop an issue.
